jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for build
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_REVIEWS: ${{ secrets.VITE_API_REVIEWS }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: main
          folder: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
